---
- name: install and start nginx
  hosts: localhost
  become: root
  tasks:
          - name: Install nginx
            apt:
                    name: nginx
                    state: present
          - name: Start nginx
            service:
                    name: nginx
                    state: started

